In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

## Question 1

###  a

In [11]:
#  Data ingestion
url="https://raw.githubusercontent.com/ek-chris/Practice_datasets/refs/heads/main/eletronic_sales.csv"
df= pd.read_csv(url)
df.head(50)
df2= df.copy()
df2.head(2)

         Date Branch Sales Agent Products  Units  Price
0  2014-09-01   Woji     Chinedu    Apple      2  125.0
1  2015-06-17   Woji       Emeka    Apple      5  125.0

In [13]:
# Datetime conversion  
df2["Date"]= pd.to_datetime(df2["Date"])

In [25]:
# Feature extraction
df2["year"]= df2["Date"].dt.year
df2["month"]= df2["Date"].dt.month_name()
df2["Day"]= df2["Date"].dt.day_name()
df2["Day_of_the_week"]= df2["Date"].dt.day_of_week
df2.head(20)

,Date,Branch,Sales Agent,Products,Units,Price,year,month,Day,Day_of_the_week,Total_sales
0,2014-09-01,Woji,Chinedu,Apple,2,125.00,2014,September,Monday,0,250.00
1,2015-06-17,Woji,Emeka,Apple,5,125.00,2015,June,Wednesday,2,625.00
2,2015-09-10,Woji,Ibrahim,Lenovo,7,1.29,2015,September,Thursday,3,9.03
3,2015-11-17,Woji,Tolu,HP,11,4.99,2015,November,Tuesday,1,54.89
4,2015-10-31,Woji,Tonye,Lenovo,14,1.29,2015,October,Saturday,5,18.06
5,2014-02-26,Woji,Ibrahim,Compaq,27,19.99,2014,February,Wednesday,2,539.73
6,2014-10-05,Woji,George,HP,28,8.99,2014,October,Sunday,6,251.72
7,2015-12-21,Woji,Tonye,HP,28,4.99,2015,December,Monday,0,139.72
8,2014-02-09,Woji,Tolu,Lenovo,36,4.99,2014,February,Sunday,6,179.64
9,2015-08-07,Woji,Emeka,Dell,42,23.95,2015,August,Friday,4,1005.90
10,2015-01-15,Woji,Ibrahim,HP,46,8.99,2015,January,Thursday,3,413.54
11,2014-01-23,Woji,Emeka,HP,50,19.99,2014,January,Thursday,3,999.50
12,2015-03-24,Woji,Tolu,Dell,50,4.99,2015,March,Tuesday,1,249.50
13,2015-05-14,Woji,Ibrahim,Lenovo,53,1.29,2015,May,Thursday,3,68.37
14,2015-07-21,Woji,George,Dell,55,12.49,2015,July,Tuesday,1,686.95
15,2015-04-10,Woji,Tonye,Lenovo,66,1.99,2015,April,Friday,4,131.34
16,2014-12-12,Woji,Chinedu,Lenovo,67,1.29,2014,December,Friday,4,86.43
17,2014-04-18,Woji,Tonye,Lenovo,75,1.99,2014,April,Friday,4,149.25
18,2015-05-31,Woji,Ibrahim,HP,80,8.99,2015,May,Sunday,6,719.20
19,2015-02-01,Woji,Chinedu,HP,87,15.00,2015,February,Sunday,6,1305.00

###  b
#

In [32]:
# Branch level Total Analysis

df2["Branch"]

df2["Total_sales"]= df2["Units"] * df2["Price"]
# Branch_total_sales= Branch["Units"] * Branch["Price"]

display_data_frame= pd.DataFrame({"Branch": df2["Branch"], "Total_sales": df2["Total_sales"]})
display_data_frame.head()

  Branch  Total_sales
0   Woji       250.00
1   Woji       625.00
2   Woji         9.03
3   Woji        54.89
4   Woji        18.06

### c

In [29]:
# Top performing Sales Agent
Brancch_level_total_analysis=otal_revenue_by_branch = df2.groupby("Sales Agent")["Total_sales"].sum().sort_values(ascending = False)
Brancch_level_total_analysis

Sales Agent
Emeka       3109.44
Chioma      3102.30
Tolu        2812.19
Blessing    2363.04
Ibrahim     1749.87
Chinedu     1641.43
George      1387.77
Uche        1283.61
Tunde       1203.11
Torbari      536.75
Tonye        438.37
Name: Total_sales, dtype: float64

### d

In [43]:
# df2.isna().sum()
# Introduce missing file
df2.loc[[5, 14, 25], 'Price']= np.nan
df2.loc[[5, 14, 25], 'Price']

5    NaN
14   NaN
25   NaN
Name: Price, dtype: float64

In [45]:
df2.loc[[5, 14, 25], 'Price'].fillna(df2["Price"].median())

5     4.99
14    4.99
25    4.99
Name: Price, dtype: float64

### e

In [46]:
Average= df2["Price"].mean()

### Question 2

### a

In [ ]:
# Create a NumPy array containing 20 random integers between 10 and 100. Then perform the following tasks

array= np.random.randint(10,100, size=20)
array

# Reshaping
reshaping= array.reshape(4, 5)
reshaping

# Extracting
extracted = reshaping[:2, -3:]
extracted


# Compute the mean and standard deviation of the entire array
mean_value = array.mean()
std_value = array.std()

mean_value, std_value

array([[37, 94, 92],
       [63, 94, 13]], dtype=int32)

### b

In [59]:
# Simulate a 2D array representing students’ scores in 5 subjects (10 students).
# Simulate a 2D array representing students’ scores in 5 subjects (10 students)
scores = np.random.randint(30, 101, size=(10, 5))
scores

# # Calculate the average score per student
average_per_student = scores.mean(axis=1)
print("average per student" ,average_per_student)

# Determine the highest and lowest score in the dataset
highest_score = scores.max()
lowest_score = scores.min()


print("highest_score", highest_score)
print("lowest", lowest_score)

average per student [66.6 73.6 68.8 47.8 82.4 67.  65.8 64.6 53.4 78.2]
highest_score 100
lowest 36

### c

In [74]:

# <!-- Create a 3D NumPy array with dimensions (3, 4, 2) filled with random integers between 1 and 20. Perform the following 
random_numbers = np.random.randint(1, 20, size=(3,4,2))
print(random_numbers)

# # Find the sum of elements across the second axis.
sum_across_second= random_numbers.sum(axis=1)
print("sum across second axis", sum_across_second)


# Compute the maximum value along each layer.

max_per_layer = random_numbers.max(axis=1)
print("Max per layer" ,max_per_layer)

# Maximum_value= 


# Flatten the entire 3D array into a 1D array
flattened_array = random_numbers.flatten()
print("flatten" ,flattened_array)

[[[ 6  5]
  [ 2  8]
  [15 17]
  [12 13]]

 [[15 17]
  [ 1  6]
  [16 18]
  [14 11]]

 [[13 10]
  [ 5  2]
  [10  8]
  [15  1]]]
sum across second axis [[35 43]
 [46 52]
 [43 21]]
Max per layer [[15 17]
 [16 18]
 [15 10]]
flatten [ 6  5  2  8 15 17 12 13 15 17  1  6 16 18 14 11 13 10  5  2 10  8 15  1]

### Question 3

``` Given the dataset of $CO_2$ emissions (in metric tons per capita) from five countries: [25.4, 30.2, 22.5, 28.1, 35.0]

<!-- Compute the mean, median, and mode. -->
mean= 25.4 + 30.2+22.5+28.1+ 5.0 / 5

mean=  141.2/5
mean=28.24
mode= the dataset has no mode
median= 28.1
 <!-- Determine the range and standard deviation. -->
range= 35.0- 22.5
     =12.5
snadard_deviation= 4.25
<!-- The spread of the data can be described by its range and standard deviation. In this dataset, the values range from 22.5 to 35.0, giving a range of 12.5. The standard deviation (calculated previously) shows how much the values deviate from the mean. Since the range and standard deviation are moderate compared to the mean, the data points are somewhat spread out but not extremely dispersed, indicating moderate variability in  -->

  emissions among the five countries.

### b

### Question 4

### a

In [84]:
student_scores= np.array([[80, 70, 90],
                          [60, 85, 75],
                          [95, 88, 92],
                          [70, 60, 65]
                          ])

# a) Total score per student

student1= student_scores[0,:].sum()
student2= student_scores[1,:].sum()
student3= student_scores[2,:].sum()
student4= student_scores[3,:].sum()

print("Total score for student 1", student1)
print("Total score for student 2", student2)
print("Total score for student 3", student3)
print("Total score for student 4", student4)

total_score_matrix_for_students=np.array([[240],[220],[275],[195]])
total_score_matrix_for_students

Total score for student 1 240
Total score for student 2 220
Total score for student 3 275
Total score for student 4 195

array([[240],
       [220],
       [275],
       [195]])

### b

In [88]:
Average_score_per_Math= student_scores[:,0]/4
Average_score_per_English= student_scores[:,1]/4
Average_score_per_science= student_scores[:,2]/4

Average_score_per_Math
Average_score_per_English
Average_score_per_science

Average_score_per_each_subject=np.array([[22.5, 18.75, 23, 16.25]])
Average_score_per_each_subject

array([[22.5 , 18.75, 23.  , 16.25]])

### c

In [ ]:
# c)Weighted Final Grades(6 marks)


student_scores= np.array([[80, 70, 90],
                          [60, 85, 75],
                          [95, 88, 92],
                          [70, 60, 65]
                          ])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)